# Generated by Django 5.1.7 on 2025-03-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabregister', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cab_images'),
        ),
    ]
