# Generated by Django 5.1.7 on 2025-03-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabregister', '0002_cabimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cab',
            name='driver_image',
            field=models.ImageField(blank=True, null=True, upload_to='driver image'),
        ),
    ]
