# Generated by Django 5.1.7 on 2025-03-25 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabregister', '0003_cab_driver_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cab',
            name='adhar',
        ),
        migrations.AddField(
            model_name='cab',
            name='car_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cab',
            name='driver_age',
            field=models.PositiveIntegerField(default=19, validators=[django.core.validators.MinValueValidator(18)]),
        ),
        migrations.AddField(
            model_name='cab',
            name='languages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cab',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cab',
            name='vehicle_type',
            field=models.CharField(choices=[('1', 'Car'), ('2', 'Auto')], max_length=150),
        ),
        migrations.DeleteModel(
            name='CabImages',
        ),
    ]
