# Generated by Django 5.1.7 on 2025-03-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabregister', '0004_remove_cab_adhar_cab_car_details_cab_driver_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cab',
            name='driver_image',
            field=models.ImageField(blank=True, null=True, upload_to='driver_image'),
        ),
        migrations.AlterField(
            model_name='cab',
            name='driving_license',
            field=models.ImageField(upload_to='driving_license'),
        ),
        migrations.AlterField(
            model_name='cab',
            name='vehicle_rc',
            field=models.ImageField(upload_to='vehicle'),
        ),
        migrations.DeleteModel(
            name='CabLocationHistory',
        ),
    ]
