# Generated by Django 5.1.7 on 2025-03-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabregister', '0005_alter_cab_driver_image_alter_cab_driving_license_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cab',
            name='price_per_km',
            field=models.PositiveIntegerField(default=40),
        ),
    ]
