# Generated by Django 5.1.7 on 2025-03-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabregister', '0006_alter_cab_price_per_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='cab',
            name='lattitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cab',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
