# Generated by Django 5.1.7 on 2025-03-25 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabregister', '0007_cab_lattitude_cab_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cab',
            old_name='lattitude',
            new_name='latitude',
        ),
    ]
